org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
minecraft_version=1.21.7
minecraft_version_range=[1.21.7,1.22)
neo_version=21.7.2-beta
neo_version_range=[21,)
loader_version_range=[4,)
parchment_minecraft_version=1.21.5
parchment_mappings_version=2025.06.15
mod_id=fallingleaves
mod_name=FallingLeaves
mod_license=LGPL-3.0
mod_version=1.0-SNAPSHOT
mod_group_id=de.cheaterpaul
mod_authors=Cheaterpaul
mod_description=How the gentle wind\nbeckons through the leaves\nas autumn colors fall,\ndancing in a swirl\nof golden memories:\nthe loveliest lies of all.
mod_credits=Thanks to Fourmisain, BrekiTomasson and RandomMcSomethin who developed this mod for fabric and published the source code with MIT license
