modLoader = "javafml"
loaderVersion = "${loader_version_range}"
issueTrackerURL = "${mod_issue_tracker_url}"
license = "${mod_license}"
displayTest="IGNORE_ALL_VERSION"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
logoFile = "logo.png"
credits = "${mod_credits}"
authors = "${mod_authors}"
description = '''${mod_description}'''
[[mixins]]
config = "fallingleaves.mixins.json"
[[dependencies.${mod_id}]] #optional
modId = "neoforge" #mandatory
type = "required"
versionRange = "${forge_version_range}" #mandatory
ordering = "NONE"
side = "CLIENT"
[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "CLIENT"