modLoader = "javafml"
loaderVersion = "[36,)"
issueTrackerURL = "https://github.com/Cheaterpaul/fallingleaves/issues"
license = "MIT"

[[mods]]
modId = "fallingleaves"
version = "${version}"
displayName="Falling Leaves"
logoFile="logo.png"
credits="Thanks to Fourmisain, BrekiTomasson and RandomMcSomethin who developed this mod for fabric and published the source code with MIT licence"
authors="Cheaterpaul, Fourmisain, BrekiTomasson and RandomMcSomethin"
description="\"How the gentle wind \nbeckons through the leaves \nas autumn colors fall,\ndancing in a swirl \nof golden memories:\nthe loveliest lies of all.\""

[[dependencies.fallingleaves]] #optional
# the modid of the dependency
modId="forge" #mandatory
# Does this dependency have to exist - if not, ordering below must be specified
mandatory=true #mandatory
# The version range of the dependency
versionRange="[36,)" #mandatory
# An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
ordering="NONE"
# Side this dependency is applied on - BOTH, CLIENT or SERVER
side="CLIENT"
# Here's another dependency
[[dependencies.fallingleaves]]
modId="minecraft"
mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
versionRange="[1.16.5,1.17)"
ordering="NONE"
side="CLIENT"