modLoader = "javafml"
loaderVersion = "${loader_version_range}"
issueTrackerURL = "${mod_issue_tracker_url}"
license = "${mod_license}"
displayTest="IGNORE_ALL_VERSION"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
logoFile = "logo.png"
credits = "${mod_credits}"
authors = "${mod_authors}"
description = '''${mod_description}'''
displayTest="IGNORE_ALL_VERSION"
[[dependencies."${mod_id}"]] #optional
modId = "forge" #mandatory
mandatory = true
versionRange = "${forge_version_range}" #mandatory
ordering = "NONE"
side = "CLIENT"
[[dependencies."${mod_id}"]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "CLIENT"