modLoader = "javafml"
loaderVersion = "[34,)"
issueTrackerURL = "https://github.com/Cheaterpaul/fallingleaves/issues"
license = "LGPL-3.0"

[[mods]]
modId = "fallingleaves"
version = "${version}"
displayName = "Falling Leaves"
logoFile = "logo.png"
credits = "Thanks to Fourmisain, BrekiTomasson and RandomMcSomethin who developed this mod for fabric and published the source code with MIT licence"
authors = "Cheaterpaul, Fourmisain, BrekiTomasson and RandomMcSomethin"
description = '''How the gentle wind
    beckons through the leaves
    as autumn colors fall,
    dancing in a swirl
    of golden memories:
    the loveliest lies of all.'''
[[dependencies.fallingleaves]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[34,)" #mandatory
ordering = "NONE"
side = "CLIENT"
[[dependencies.fallingleaves]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.3,1.17)"
ordering = "NONE"
side = "CLIENT"