name: publish.yml
on:
  release:
    types:
      - released
      - prereleased

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      mc_version: ${{ steps.extract.outputs.mc_version }}
      mod_version: ${{ steps.extract.outputs.mod_version }}
      version_type: ${{ steps.extract.outputs.version_type }}
    steps:
      - name: "Extract"
        id: extract
        env:
          TAG: ${{ github.event.release.tag_name }}
        run: |
          mc_version="${TAG%%-*}"
          rest="${TAG#"$mc_version"-}"

          if [[ "$rest" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            version_type="release"
          elif [[ "$rest" =~ ^[0-9]+\.[0-9]+\.[0-9]+-beta$ ]]; then
            version_type="beta"
          else
            version_type="alpha"
          fi

          echo "mc_version=$mc_version" >> "$GITHUB_OUTPUT"
          echo "mod_version=$TAG" >> "$GITHUB_OUTPUT"
          echo "version_type=$version_type" >> "$GITHUB_OUTPUT"

  build:
    needs: [ prepare]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'gradle'
      - name: Setup Gradle
        run: ./gradlew
      - name: Build
        run: ./gradlew build -Pmod_version=${{ needs.prepare.outputs.mod_version }}
      - name: Upload Jars
        uses: actions/upload-artifact@v6
        with:
          name: jar
          path: |
            build/libs/*.jar
          retention-days: 2


  publish:
    needs: [prepare, build]
    runs-on: ubuntu-latest
    steps:
      - name: Get Artifacts
        uses: actions/download-artifact@v6
        with:
          name: jar
          path: build/libs
      - name: Publish
        uses: Kir-Antipov/mc-publish@v3
        with:
          curseforge-id: ${{ vars.CURSEFORGE_ID }}
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          modrinth-id: ${{ vars.MODRINTH_ID }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          files: build/libs/fallingleaves-${{  needs.prepare.outputs.mod_version }}.jar
          name: FallingLeaves ${{  needs.prepare.outputs.mod_version }}
          version: ${{  needs.prepare.outputs.mod_version }}
          version-type: ${{  needs.prepare.outputs.version_type }}
          changelog: ${{ github.event.release.body }}
          environment: client
          game-versions: |
            ${{ needs.prepare.outputs.mc_version }}
          loaders: |
            neoforge